version: "3.8"

services:
  db:
    image: postgres:15
    env_file:
      - .env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app/backend
      - /app/backend/data
    ports:
      - "8000:8000"
    env_file:
      - .env.local   # variáveis do Django ficam aqui (SECRET_KEY, SQL_…, DJANGO_DEBUG, NEXT_PUBLIC_API_URL NÃO precisa)
      - .env.db
    depends_on:
      - db

  frontend:
    build: ./frontend
    command: npm run dev
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  postgres_data:
