# Generated by Django 5.0.6 on 2025-08-14 14:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=160)),
                ('etapa', models.CharField(choices=[('fundacao', 'Fundação'), ('estrutura', 'Estrutura'), ('fechamentos', 'Fechamentos'), ('cobertura', 'Cobertura/Laje'), ('acabamentos', 'Acabamentos/Instalações'), ('transp_mo', 'Transporte/Mão de Obra'), ('demolicao', 'Demolição')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Desperdicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('etapa', models.CharField(blank=True, choices=[('fundacao', 'Fundação'), ('estrutura', 'Estrutura'), ('fechamentos', 'Fechamentos'), ('cobertura', 'Cobertura/Laje'), ('acabamentos', 'Acabamentos/Instalações'), ('transp_mo', 'Transporte/Mão de Obra'), ('demolicao', 'Demolição')], max_length=20, null=True)),
                ('percentual', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2, unique=True)),
                ('nome', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='FatorTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('energia_MJ_por_t_km', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=12)),
                ('co2e_kg_por_t_km', models.DecimalField(decimal_places=6, default=Decimal('0.070000'), max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160, unique=True)),
                ('unidade_base', models.CharField(default='kg', help_text='Unidade canônica: kg, m2, un, etc.', max_length=20)),
                ('densidade_kg_m3', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('energia_MJ_por_un', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('co2e_kg_por_un', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('energia_MJ_por_kg', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('co2e_kg_por_kg', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParametrosOperacionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('fator_kcal_por_hora_pessoa', models.DecimalField(decimal_places=2, default=Decimal('250.00'), max_digits=10)),
                ('pessoas_por_equipe', models.IntegerField(default=3)),
                ('horas_por_dia', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5)),
                ('fator_kgCO2e_por_GJ', models.DecimalField(decimal_places=4, default=Decimal('74.1000'), max_digits=10)),
                ('fator_kgCO2e_eletricidade_por_GJ', models.DecimalField(decimal_places=4, default=Decimal('63.1000'), max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('codigo_ibge', models.CharField(blank=True, max_length=10, null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidades', to='core.estado')),
            ],
            options={
                'unique_together': {('estado', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='ItemDeComposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade_medida', models.CharField(help_text='ex: m2, un, kg', max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('desperdicio_pct', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='% 0-100', max_digits=6)),
                ('composicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.composicao')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='core.material')),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('area_construida_m2', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('fundacao_codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('supra_estrutura_1_codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('supra_estrutura_2_codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('fechamentos_codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('telhado_codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('piso_codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obras', to='core.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='DistanciaInsumoCidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distancias_insumo', to='core.cidade')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distancias', to='core.material')),
            ],
            options={
                'unique_together': {('material', 'cidade')},
            },
        ),
        migrations.CreateModel(
            name='ConversaoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_unidade', models.CharField(max_length=20)),
                ('destino_unidade', models.CharField(default='kg', max_length=20)),
                ('espessura_m', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('fator_massa_kg_por_origem', models.DecimalField(decimal_places=6, max_digits=16)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversoes', to='core.material')),
            ],
            options={
                'unique_together': {('material', 'origem_unidade', 'destino_unidade', 'espessura_m')},
            },
        ),
    ]
