# Generated by Django 5.2 on 2025-05-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('densidade_kg_m3', models.FloatField()),
                ('energia_embutida_mj_kg', models.FloatField()),
                ('co2eq_kg', models.FloatField()),
                ('fator_manutencao', models.FloatField(default=1.0)),
                ('distancia_transporte_km', models.FloatField()),
                ('referencia', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Obras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipologia', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=100)),
                ('area_construida', models.FloatField(help_text='Área construída em m²')),
            ],
        ),
    ]
