# Generated by Django 5.2.1 on 2025-05-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_insumousado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obras',
            name='area_construida',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='obras',
            name='tipologia',
            field=models.CharField(max_length=50),
        ),
    ]
