# Generated by Django 5.2.1 on 2025-05-29 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_obras_area_construida_alter_obras_tipologia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='material',
            name='co2eq_kg',
        ),
        migrations.RemoveField(
            model_name='material',
            name='densidade_kg_m3',
        ),
        migrations.RemoveField(
            model_name='material',
            name='distancia_transporte_km',
        ),
        migrations.RemoveField(
            model_name='material',
            name='nome',
        ),
        migrations.AddField(
            model_name='material',
            name='capacidade_caminhao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='co2_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='densidade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='descricao',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='energia_embutida_mj_m3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='referencia_para_cuiaba',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='energia_embutida_mj_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='fator_manutencao',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='referencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='DistanciaTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.FloatField()),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cidade')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material')),
            ],
        ),
    ]
