# Generated by Django 5.2.1 on 2025-06-03 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cidade_remove_material_co2eq_kg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField()),
                ('unidade', models.CharField(max_length=10)),
                ('etapa_obra', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='obras',
            name='area_construida',
        ),
        migrations.RemoveField(
            model_name='obras',
            name='localizacao',
        ),
        migrations.AddField(
            model_name='obras',
            name='area_terreno',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='area_total_construir',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='area_total_demolir',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='certificacao_obra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='obras',
            name='certificacao_obra_tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='custo_final_apurado',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='custo_inicial_estimado',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='data_inicio_construcao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='data_termino_construcao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='financiamento_publico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='obras',
            name='logradouro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='municipio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='numero_pavimentos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='numero_unidades',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='padrao_empreendimento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='razao_social',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='segmentacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='sistema_construtivo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='tipo_empreendimento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='tipo_registro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ComposicaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(max_length=10)),
                ('proporcao', models.FloatField()),
                ('composicao_pai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.composicao')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.material')),
                ('subcomposicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_itens', to='core.composicao')),
            ],
        ),
        migrations.CreateModel(
            name='ItemLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INSUMO', 'INSUMO'), ('COMPOSICAO', 'COMPOSICAO')], max_length=20)),
                ('etapa_obra', models.CharField(max_length=100)),
                ('unidade', models.CharField(blank=True, max_length=10, null=True)),
                ('proporcao', models.FloatField(blank=True, null=True)),
                ('quantidade', models.FloatField(blank=True, null=True)),
                ('equivalente_kg', models.FloatField(blank=True, null=True)),
                ('energia_embutida_mj', models.FloatField(blank=True, null=True)),
                ('energia_embutida_gj', models.FloatField(blank=True, null=True)),
                ('co2_kg', models.FloatField(blank=True, null=True)),
                ('distancia_km', models.FloatField(blank=True, null=True)),
                ('energia_transporte_mj', models.FloatField(blank=True, null=True)),
                ('energia_transporte_gj', models.FloatField(blank=True, null=True)),
                ('potencia_w', models.FloatField(blank=True, null=True)),
                ('tempo_uso', models.FloatField(blank=True, null=True)),
                ('energia_equip_mj', models.FloatField(blank=True, null=True)),
                ('energia_equip_gj', models.FloatField(blank=True, null=True)),
                ('percentual_total', models.FloatField(blank=True, null=True)),
                ('composicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.composicao')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.material')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_lista', to='core.obras')),
            ],
        ),
        migrations.DeleteModel(
            name='InsumoUsado',
        ),
    ]
