# Generated by Django 5.2.1 on 2025-06-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_composicao_remove_obras_area_construida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='composicaoitem',
            name='co2_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='composicaoitem',
            name='energia_embutida_gj',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='composicaoitem',
            name='energia_embutida_mj',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='composicaoitem',
            name='quantidade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
