# Generated by Django 5.2.1 on 2025-06-04 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_composicaoitem_co2_kg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composicaoitem',
            name='material',
        ),
        migrations.RemoveField(
            model_name='distanciatransporte',
            name='material',
        ),
        migrations.RemoveField(
            model_name='itemlista',
            name='material',
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sinapi', models.CharField(max_length=20, unique=True)),
                ('descricao', models.TextField()),
                ('unidade', models.CharField(max_length=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.material')),
            ],
        ),
        migrations.AddField(
            model_name='composicaoitem',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.insumo'),
        ),
        migrations.AddField(
            model_name='distanciatransporte',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.insumo'),
        ),
        migrations.AddField(
            model_name='itemlista',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.insumo'),
        ),
    ]
