# Generated by Django 5.2.1 on 2025-06-04 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_composicaoitem_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composicaoitem',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='composicao_items', to='core.insumo'),
        ),
        migrations.AlterField(
            model_name='composicaoitem',
            name='proporcao',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='composicaoitem',
            name='subcomposicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='como_subcomposicao', to='core.composicao'),
        ),
    ]
