# Generated by Django 5.2.1 on 2025-06-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_composicaoitem_insumo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='composicaoitem',
            name='valido',
            field=models.BooleanField(default=True),
        ),
    ]
