# Generated by Django 5.2.1 on 2025-06-30 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_composicaoitem_valido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obras',
            old_name='certificacao_obra_tipo',
            new_name='cidade',
        ),
        migrations.RemoveField(
            model_name='obras',
            name='certificacao_obra',
        ),
        migrations.RemoveField(
            model_name='obras',
            name='custo_final_apurado',
        ),
        migrations.RemoveField(
            model_name='obras',
            name='custo_inicial_estimado',
        ),
        migrations.RemoveField(
            model_name='obras',
            name='data_inicio_construcao',
        ),
        migrations.RemoveField(
            model_name='obras',
            name='data_termino_construcao',
        ),
        migrations.RemoveField(
            model_name='obras',
            name='financiamento_publico',
        ),
        migrations.RemoveField(
            model_name='obras',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='obras',
            name='numero_pavimentos',
        ),
        migrations.RemoveField(
            model_name='obras',
            name='numero_unidades',
        ),
        migrations.RemoveField(
            model_name='obras',
            name='padrao_empreendimento',
        ),
        migrations.RemoveField(
            model_name='obras',
            name='razao_social',
        ),
        migrations.RemoveField(
            model_name='obras',
            name='segmentacao',
        ),
        migrations.RemoveField(
            model_name='obras',
            name='sistema_construtivo',
        ),
        migrations.RemoveField(
            model_name='obras',
            name='tipo_empreendimento',
        ),
        migrations.RemoveField(
            model_name='obras',
            name='tipo_registro',
        ),
        migrations.CreateModel(
            name='EtapaObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dados', models.JSONField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas_tecnicas', to='core.obras')),
            ],
        ),
    ]
