# Generated by Django 5.2.1 on 2025-06-30 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_certificacao_obra_tipo_obras_cidade_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DistanciaTransporte',
            new_name='DistanciaInsumoCidade',
        ),
        migrations.RemoveField(
            model_name='itemlista',
            name='composicao',
        ),
        migrations.RemoveField(
            model_name='itemlista',
            name='insumo',
        ),
        migrations.RemoveField(
            model_name='itemlista',
            name='obra',
        ),
        migrations.CreateModel(
            name='ItemDeComposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(max_length=10)),
                ('proporcao', models.FloatField(blank=True, null=True)),
                ('valido', models.BooleanField(default=True)),
                ('composicao_pai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.composicao')),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='composicao_items', to='core.insumo')),
                ('subcomposicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='como_subcomposicao', to='core.composicao')),
            ],
        ),
        migrations.RenameModel(
            old_name='EtapaObra',
            new_name='EtapaConstrutiva',
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipologia', models.CharField(max_length=50)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=100, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('area_terreno', models.FloatField(blank=True, null=True)),
                ('area_total_construir', models.FloatField(blank=True, null=True)),
                ('area_total_demolir', models.FloatField(blank=True, null=True)),
                ('cidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='InsumoAplicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INSUMO', 'INSUMO'), ('COMPOSICAO', 'COMPOSICAO')], max_length=20)),
                ('etapa_obra', models.CharField(max_length=100)),
                ('unidade', models.CharField(blank=True, max_length=10, null=True)),
                ('proporcao', models.FloatField(blank=True, null=True)),
                ('quantidade', models.FloatField(blank=True, null=True)),
                ('equivalente_kg', models.FloatField(blank=True, null=True)),
                ('energia_embutida_mj', models.FloatField(blank=True, null=True)),
                ('energia_embutida_gj', models.FloatField(blank=True, null=True)),
                ('co2_kg', models.FloatField(blank=True, null=True)),
                ('distancia_km', models.FloatField(blank=True, null=True)),
                ('energia_transporte_mj', models.FloatField(blank=True, null=True)),
                ('energia_transporte_gj', models.FloatField(blank=True, null=True)),
                ('potencia_w', models.FloatField(blank=True, null=True)),
                ('tempo_uso', models.FloatField(blank=True, null=True)),
                ('energia_equip_mj', models.FloatField(blank=True, null=True)),
                ('energia_equip_gj', models.FloatField(blank=True, null=True)),
                ('percentual_total', models.FloatField(blank=True, null=True)),
                ('composicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.composicao')),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.insumo')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_aplicados', to='core.obra')),
            ],
        ),
        migrations.AlterField(
            model_name='etapaconstrutiva',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas_tecnicas', to='core.obra'),
        ),
        migrations.DeleteModel(
            name='ComposicaoItem',
        ),
        migrations.DeleteModel(
            name='ItemLista',
        ),
        migrations.DeleteModel(
            name='Obras',
        ),
    ]
