# Generated by Django 5.2.1 on 2025-07-17 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_distanciatransporte_distanciainsumocidade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['descricao'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materiais'},
        ),
        migrations.AddField(
            model_name='composicao',
            name='tipo',
            field=models.CharField(choices=[('SERVICO', 'Serviço'), ('COMPOSICAO', 'Composição'), ('INSUMO', 'Insumo')], default='COMPOSICAO', max_length=15),
        ),
        migrations.CreateModel(
            name='ImpactoInsumoComposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(max_length=10)),
                ('proporcao', models.FloatField()),
                ('quantidade', models.FloatField(blank=True, null=True)),
                ('energia_embutida_total', models.FloatField(blank=True, null=True)),
                ('carbono_embutido', models.FloatField(blank=True, null=True)),
                ('carbono_transporte', models.FloatField(blank=True, null=True)),
                ('carbono_manutencao', models.FloatField(blank=True, null=True)),
                ('carbono_despesa', models.FloatField(blank=True, null=True)),
                ('carbono_total', models.FloatField(blank=True, null=True)),
                ('composicao_pai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.composicao')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.insumo')),
            ],
        ),
    ]
