# Generated by Django 5.2.1 on 2025-07-17 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_material_options_composicao_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.material'),
        ),
    ]
