# Generated by Django 5.2.1 on 2025-07-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_estado_alter_cidade_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='co2_total_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='energia_total_mj',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
