# Generated by Django 5.2.1 on 2025-08-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_obra_co2_total_kg_obra_energia_total_mj'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='radier_area_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='radier_espessura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='superestrutura_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='superestrutura_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='tipologia_fundacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='tipologia_vedacao_externa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='tipologia_vedacao_interna',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
